mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin, auth
from django.views.generic.base import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^task/', include('tasks.urls', namespace="tasks")),
    url(r'^account/', include('django.contrib.auth.urls', namespace="account")),
    url(r'^$',RedirectView.as_view(pattern_name="tasks:task_list"))
]

tasks/urls.py
from django.conf.urls import url
from .views import TaskListView, TaskCreateView, TaskUpdateView, TaskDeleteView, signup

urlpatterns = [
    url(r'^list/$', TaskListView.as_view(),name = "task_list"),
    url(r'^add/$', TaskCreateView.as_view(), name = "task_add"),
    url(r'^edit/(?P<pk>\d+)/$', TaskUpdateView.as_view(), name='task_edit',),
    url(r'^delete/(?P<pk>\d+)/$', TaskDeleteView.as_view(), name='task_delete',),
    url(r'^signup/$', signup, name='signup')
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User)
    title = models.CharField(max_length=50)
    time_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    description = models.TextField()
    due_date = models.DateTimeField()

    def __str__(self):
        return self.title

class Bucket(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return self.title

class TaskBucket(models.Model):
    task = models.ForeignKey(Task)
    bucket = models.ForeignKey(Bucket)
    last_modified = models.DateTimeField(auto_now=True)
    priority = models.CharField(max_length=60)

    def __str__(self):
        return self.task.title +" -- " + self.bucket.title

tasks/forms.py
from django import forms

class TaskForm(forms.Form):
    title = forms.CharField(max_length=50)
    description = forms.Textarea()
    due_date = forms.DateTimeField()

tasks/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth import login, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm



from .models import Task


# Create your views here.


class TaskListView(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "tasks/task_list.html"

    def get_queryset(self):
        return Task.objects.filter(user=self.request.user)


class TaskCreateView(LoginRequiredMixin, CreateView):
    model = Task
    context_object_name = "task"
    template_name = "tasks/task_add.html"
    fields = ['title', 'description','due_date']
    success_url = reverse_lazy('tasks:task_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreateView, self).form_valid(form)


class TaskUpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    fields = ['title', 'description','due_date']
    context_object_name ="task"
    template_name_suffix = "_update_form"
    success_url = reverse_lazy('tasks:task_list')

    def get_queryset(self):
        base_qs = super(TaskUpdateView, self).get_queryset()
        return base_qs.filter(user=self.request.user)


class TaskDeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:task_list')
    context_object_name = "task"

    def get_queryset(self):
        base_qs = super(TaskDeleteView, self).get_queryset()
        return base_qs.filter(user=self.request.user)


## This should be broken out into a separate app
def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=raw_password)
            login(request,user)
            return redirect('tasks:task_list')
    else:
        form = UserCreationForm()
    return render(request, 'tasks/signup.html', {'form':form})

tasks/templates/tasks/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

tasks/templates/tasks/task_add.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <form class="col s12" action="" method="post">{% csrf_token %}
                {{ form.as_p }}
                <input class="waves-effect waves-light btn" type="submit" value="Save" />
            </form>
        </div>
    </div>

{% endblock %}

tasks/templates/tasks/task_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <input class= "waves-effect waves-light btn" type="submit" value="Confirm" />
        </form>
    </div>

{% endblock %}

tasks/templates/tasks/task_list.html
{% extends 'base.html' %}

{% block content %}
<div class="section no-pad-bot" id="index-banner">
  <div class="container">
      {%  for task in tasks %}
      <div class="row">
        <div class="col s12 m6">
          <div class="card blue-grey darken-1">
            <div class="card-content white-text">
              <span class="card-title">{{task.title}}</span>
              <p>{{ task.description }}</p>
            </div>
            <div class="card-action">
              <a href="{% url 'tasks:task_edit' task.id%}">Edit</a>
              <a href="{% url 'tasks:task_delete' task.id %}">Delete</a>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
  </div>
</div>
<a class="btn-floating btn-large waves-effect waves-light red" href="{% url 'tasks:task_add' %}"><i class="material-icons">add</i></a>
{% endblock %}

tasks/templates/tasks/task_update_form.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <form class="col s12" action="" method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="waves-effect waves-light btn" type="submit" value="Save" />
    </form>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Task Master</title>

  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="#" class="brand-logo">Task Master</a>
      <ul class="right hide-on-med-and-down">
          {% if user.is_authenticated %}
        <li ><a href="{% url  'account:logout' %}">logout</a></li>
          {% endif %}
      </ul>


      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>
{% block content %}
  {% endblock %}


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">


<script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  </body>
</html>